### ISSUE TITLE
Writing `ArrayBuffer` instead of `Buffer`

### ISSUE THREAD

**Issue by jamen** [audiojs/audio-mpg123#5]
This would be nice so we don't have to convert the audio to `Buffer` inside `audio-speaker`

**Comment by dfcreative** [comment]
@jamen in node we don't have option but using [`audio-buffer`](https://github.com/audiojs/audio-buffer), and it has planar float32 format, so you can easily obtain it as `audioBuffer._data` for a single Float32Array or `audioBuffer._channelData` for array with data separated by channels.

**Comment by jamen** [comment]
@dfcreative I [got it setup with `ArrayBuffer`](https://github.com/audiojs/audio-mpg123/blob/napi/src/audio-mpg123.cc#L119-L127) for Node in the [NAPI branch](https://github.com/audiojs/audio-mpg123/pull/10) already. 

Some related NAPI docs:

 - [Working with JavaScript attributes](https://nodejs.org/dist/latest-v8.x/docs/api/n-api.html#n_api_working_with_javascript_properties)
 - [`napi_get_property_names`](https://nodejs.org/dist/latest-v8.x/docs/api/n-api.html#n_api_napi_get_property_names)
 - [`napi_get_property`](https://nodejs.org/dist/latest-v8.x/docs/api/n-api.html#n_api_napi_get_property)

**Comment by dfcreative** [comment]
Ok, that is awesome, I think we should not change anything since we accept ArrayBuffers. We can easily cast AudioBuffer to ArrayBuffer in audio-speaker.
